name: autoSyncMergedPullRequest
on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo The PR ${{ github.event.pull_request.number }} was merged!
          echo ${{ github.event.pull_request }}
          echo "$GITHUB_CONTEXT"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.AUTOSYNC_TOKEN_CLOUD_HOSTED_REPO }}
          repository: ${{ secrets.AUTOSYNC_CLOUD_HOSTED_REPO_URL }}
          event-type: ${{ secrets.AUTOSYNC_EVENT_TYPE }}
          client-payload: '{"ref": "${{ github.ref }}", "prNumber": "${{ github.event.pull_request.number }}", "sha": "${{ github.sha }}"}'
